
name: Test
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: OS ${{ matrix.os }} with BUILD_SHARED_LIBS=${{matrix.shared}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        shared: [ON, OFF]

    steps:
     - uses: actions/checkout@v4
     - uses: ilammy/msvc-dev-cmd@v1
       if: matrix.os == 'windows-latest'
     - name: Support longpaths
       run: git config --system core.longpaths true
       if: matrix.os == 'windows-latest'
     - uses: mamba-org/setup-micromamba@v1
       with:
           init-shell: bash
           environment-file: ./github/environment.yml
           environment-name: "build"
           cache-environment: true
           cache-downloads: true

     - name: Setup
       shell: bash -l {0}
       run: |
           mkdir build
       working-directory: ./libgeotiff

     - name: CMake
       shell: bash -l {0}
       env:
        BUILD_SHARED_LIBS: ${{ matrix.shared }}

       run: |

        if [ "$RUNNER_OS" == "Windows" ]; then
        export CC=cl.exe
        export CXX=cl.exe
        fi

        cmake   -G "Ninja"  \
              -DCMAKE_BUILD_TYPE=RelWithDebInfo \
              -DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS \
              -DBUILD_TESTING=ON \
              -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} \
              ..


       working-directory: ./libgeotiff/build

     - name: Compile
       shell: bash -l {0}
       run: |
          ninja
       working-directory: ./libgeotiff/build

